import { NextResponse } from "next/server";
import connectDB from "@/lib/mongodb";
import Ghat from "@/models/Ghat";
import Service from "@/models/Service";
import Product from "@/models/Product";
import Pandit from "@/models/Pandit";
import Review from "@/models/Review";

const SEED_DATA = {
  ghats: [
    {
      name: { en: "Dashashwamedh Ghat", hi: "दशाश्वमेध घाट" },
      slug: "dashashwamedh-ghat",
      description: "The most famous and oldest ghat in Varanasi, known for the spectacular Ganga Aarti ceremony held every evening. This ghat is one of the most vibrant and holy spots in Kashi, attracting thousands of devotees and tourists daily. The name 'Dashashwamedh' means 'ten horse sacrifices' and is linked to a mythological tale of Brahma performing the Dashashwamedh Yagna here.",
      shortDescription: "Varanasi's most iconic ghat, home to the daily Ganga Aarti ceremony.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Dashashwamedh Ghat" }],
      location: { address: "Dashashwamedh Ghat, Varanasi, UP 221001" },
      capacity: 500,
      facilities: ["Boat Rides", "Aarti Viewing", "Photography Spots", "Priest Services", "Restrooms"],
      suitableFor: ["Ganga Aarti", "Puja", "Photography", "Meditation", "Boat Ride"],
      price: 2100,
      rating: 4.8,
      reviewsCount: 245,
      isActive: true,
      featured: true,
    },
    {
      name: { en: "Manikarnika Ghat", hi: "मणिकर्णिका घाट" },
      slug: "manikarnika-ghat",
      description: "Manikarnika Ghat is one of the holiest cremation ghats in India. Hindus believe that being cremated here provides moksha (liberation from the cycle of birth and death). The eternal flame that has been burning here for thousands of years is considered sacred.",
      shortDescription: "The most sacred cremation ghat, believed to grant moksha.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Manikarnika Ghat" }],
      location: { address: "Manikarnika Ghat, Varanasi, UP 221001" },
      capacity: 200,
      facilities: ["Priest Services", "Prayer Hall"],
      suitableFor: ["Last Rites", "Spiritual Meditation", "Prayer"],
      price: 5100,
      rating: 4.9,
      reviewsCount: 89,
      isActive: true,
      featured: true,
    },
    {
      name: { en: "Assi Ghat", hi: "अस्सी घाट" },
      slug: "assi-ghat",
      description: "Assi Ghat is the southernmost ghat of Varanasi, located at the confluence of the Assi and Ganges rivers. It is a popular spot for morning rituals, yoga sessions, and cultural events. The ghat has a large Shiva lingam under a peepal tree where devotees perform puja.",
      shortDescription: "Southernmost ghat, popular for morning rituals and yoga.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Assi Ghat" }],
      location: { address: "Assi Ghat, Varanasi, UP 221005" },
      capacity: 300,
      facilities: ["Yoga Area", "Meditation Space", "Boat Rides", "Cafes Nearby", "Restrooms"],
      suitableFor: ["Morning Puja", "Yoga", "Meditation", "Cultural Events"],
      price: 1500,
      rating: 4.6,
      reviewsCount: 178,
      isActive: true,
      featured: true,
    },
    {
      name: { en: "Tulsi Ghat", hi: "तुलसी घाट" },
      slug: "tulsi-ghat",
      description: "Named after the great poet-saint Tulsidas who is believed to have written the Ramcharitmanas here. This ghat hosts the famous Dev Deepawali celebrations and offers a more serene atmosphere compared to the busier ghats.",
      shortDescription: "Historic ghat associated with poet-saint Tulsidas.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Tulsi Ghat" }],
      location: { address: "Tulsi Ghat, Varanasi, UP 221001" },
      capacity: 200,
      facilities: ["Prayer Area", "Cultural Events", "Boat Rides"],
      suitableFor: ["Puja", "Dev Deepawali", "Meditation", "Cultural Programs"],
      price: 1800,
      rating: 4.5,
      reviewsCount: 92,
      isActive: true,
      featured: false,
    },
    {
      name: { en: "Harishchandra Ghat", hi: "हरिश्चंद्र घाट" },
      slug: "harishchandra-ghat",
      description: "Named after the legendary King Harishchandra known for his truthfulness, this is the oldest cremation ghat in Varanasi. It holds immense spiritual significance for Hindus performing last rites.",
      shortDescription: "Oldest cremation ghat, named after King Harishchandra.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Harishchandra Ghat" }],
      location: { address: "Harishchandra Ghat, Varanasi, UP 221001" },
      capacity: 150,
      facilities: ["Priest Services", "Prayer Hall"],
      suitableFor: ["Last Rites", "Prayer", "Spiritual Pilgrimage"],
      price: 5100,
      rating: 4.7,
      reviewsCount: 45,
      isActive: true,
      featured: false,
    },
    {
      name: { en: "Kedar Ghat", hi: "केदार घाट" },
      slug: "kedar-ghat",
      description: "Kedar Ghat is adorned with a beautiful red and white striped temple dedicated to Lord Shiva. The ghat is named after the Kedareshwar temple situated here, which is one of the most important Shiva temples in Varanasi.",
      shortDescription: "Beautiful ghat with the Kedareshwar Shiva temple.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Kedar Ghat" }],
      location: { address: "Kedar Ghat, Varanasi, UP 221001" },
      capacity: 250,
      facilities: ["Shiva Temple", "Prayer Area", "Boat Rides", "Photography Spots"],
      suitableFor: ["Shiva Puja", "Temple Visit", "Photography", "Meditation"],
      price: 1500,
      rating: 4.4,
      reviewsCount: 67,
      isActive: true,
      featured: false,
    },
  ],

  services: [
    {
      name: "Ganga Aarti Ceremony",
      slug: "ganga-aarti-ceremony",
      category: "puja-festival",
      description: "Witness and participate in the world-famous Ganga Aarti ceremony at Dashashwamedh Ghat. This ancient ritual involves large brass lamps, chanting of mantras, and the offering of fire to the sacred Ganges. Our package includes reserved front-row seating, explanation of rituals in English/Hindi, and blessed prasad.",
      shortDescription: "Participate in the iconic Ganga Aarti with reserved seating.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Ganga Aarti" }],
      duration: "1.5 hours",
      price: 2100,
      inclusions: ["Reserved front-row seating", "Aarti thali with flowers and diya", "Prasad", "English/Hindi guide", "Photography assistance"],
      requirements: ["Arrive 30 minutes before sunset", "Modest clothing recommended"],
      isActive: true,
      featured: true,
    },
    {
      name: "Rudrabhishek Puja",
      slug: "rudrabhishek-puja",
      category: "puja-festival",
      description: "Rudrabhishek is one of the most powerful and sacred Shiva pujas, performed to invoke the blessings of Lord Shiva. The puja involves abhishek (bathing) of Shiva Lingam with milk, honey, curd, ghee, and holy water while chanting the sacred Rudram mantra. Ideal for seeking health, prosperity, and spiritual growth.",
      shortDescription: "Sacred Shiva puja for health, prosperity, and spiritual growth.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Rudrabhishek Puja" }],
      duration: "2-3 hours",
      price: 5100,
      inclusions: ["Experienced Pandit Ji", "All puja samagri", "Abhishek materials", "Prasad", "Puja video recording"],
      requirements: ["Fasting recommended", "White or light-colored clothing", "Arrive on empty stomach for best results"],
      isActive: true,
      featured: true,
    },
    {
      name: "Satyanarayan Katha",
      slug: "satyanarayan-katha",
      category: "puja-festival",
      description: "Satyanarayan Katha is a puja performed to seek the blessings of Lord Vishnu (Satyanarayan). This puja is especially performed on Purnima (full moon day) and is believed to bring happiness, prosperity, and fulfill wishes. The katha involves recitation of the five chapters of Satyanarayan Vrat Katha.",
      shortDescription: "Lord Vishnu puja for happiness, prosperity, and wish fulfillment.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Satyanarayan Puja" }],
      duration: "3-4 hours",
      price: 3500,
      inclusions: ["Pandit Ji", "Complete puja samagri", "Katha recitation", "Prasad preparation", "Aarti"],
      requirements: ["Fasting recommended till puja completion", "Clean puja space needed"],
      isActive: true,
      featured: true,
    },
    {
      name: "Kaal Sarp Dosh Nivaran Puja",
      slug: "kaal-sarp-dosh-nivaran",
      category: "puja-festival",
      description: "Kaal Sarp Dosh Nivaran Puja is performed to mitigate the effects of Kaal Sarp Yoga in one's horoscope. This powerful puja is especially effective when performed in Varanasi at sacred Shiva temples. The ritual involves Nag Puja, havan, and specific mantra chanting to neutralize the dosham.",
      shortDescription: "Powerful remedy for Kaal Sarp Dosh in horoscope.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Kaal Sarp Dosh Puja" }],
      duration: "4-5 hours",
      price: 7500,
      inclusions: ["Expert Pandit Ji", "Nag Puja materials", "Havan samagri", "Specific yantras", "Energized rudraksha"],
      requirements: ["Horoscope/Kundli required", "Specific date selection based on nakshatra", "Both partners recommended for married individuals"],
      isActive: true,
      featured: false,
    },
    {
      name: "Pitru Dosh Nivaran Puja",
      slug: "pitru-dosh-nivaran",
      category: "puja-festival",
      description: "Pitru Dosh Nivaran Puja is performed to appease the departed ancestors and seek their blessings. This puja is especially powerful when performed in Varanasi during Pitru Paksha. It helps remove obstacles caused by Pitru Dosh in the horoscope.",
      shortDescription: "Ancestral blessing puja to remove Pitru Dosh.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Pitru Puja" }],
      duration: "3-4 hours",
      price: 5500,
      inclusions: ["Experienced Pandit Ji", "Pind Daan materials", "Tarpan materials", "Prasad"],
      requirements: ["Family details of departed ancestors", "Preferably performed during Pitru Paksha"],
      isActive: true,
      featured: false,
    },
    {
      name: "Traditional Hindu Wedding",
      slug: "traditional-hindu-wedding",
      category: "marriage-celebration",
      description: "Experience the grandeur of a traditional Hindu wedding ceremony in the holy city of Varanasi. Our comprehensive wedding package includes all Vedic rituals performed by experienced pandits at your chosen ghat or venue. From Ganesh Puja to Saptapadi, every ritual is performed with authentic Vedic mantras.",
      shortDescription: "Complete traditional Hindu wedding ceremony in Varanasi.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Hindu Wedding" }],
      duration: "4-6 hours",
      price: 51000,
      priceNote: "Starting from. Custom packages available.",
      inclusions: ["Head Pandit Ji + assistant", "Complete wedding samagri", "Mandap decoration", "Sacred fire (Havan Kund)", "Wedding documentation", "Photography coordination"],
      requirements: ["Venue booking separate", "Kundli matching recommended", "Guest list for arrangements", "Minimum 7 days advance booking"],
      isActive: true,
      featured: true,
    },
    {
      name: "Ganga Kinare Wedding",
      slug: "ganga-kinare-wedding",
      category: "marriage-celebration",
      description: "A dreamy wedding on the banks of the holy Ganga. This unique destination wedding package combines the spiritual significance of Varanasi with a spectacular riverside ceremony. Exchange vows with the gentle sound of the Ganga flowing by and diyas floating on the water.",
      shortDescription: "Spectacular riverside wedding on the banks of the Ganga.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Riverside Wedding" }],
      duration: "Full Day",
      price: 151000,
      priceNote: "Comprehensive package. Customizable.",
      inclusions: ["Ghat venue arrangement", "Head Pandit + team", "Boat procession", "Floral decorations", "Lighting & diyas", "Photography & videography coordination", "Guest coordination"],
      requirements: ["Advance booking: minimum 30 days", "Guest count for arrangements", "Ghat permission (we handle this)", "Weather backup plan included"],
      isActive: true,
      featured: true,
    },
    {
      name: "Engagement Ceremony (Sagai/Ring Ceremony)",
      slug: "engagement-ceremony",
      category: "marriage-celebration",
      description: "Celebrate your engagement with traditional Vedic blessings in Varanasi. Our engagement ceremony package includes ring ceremony rituals, Ganesh Puja, and blessings from experienced pandits. Can be arranged at a ghat, temple, or private venue.",
      shortDescription: "Traditional Vedic engagement ceremony with all rituals.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Engagement Ceremony" }],
      duration: "2-3 hours",
      price: 15000,
      inclusions: ["Pandit Ji", "Puja samagri", "Ring ceremony rituals", "Venue decoration (basic)", "Prasad"],
      requirements: ["Rings to be provided by family", "Guest count for seating", "5 days advance booking"],
      isActive: true,
      featured: false,
    },
  ],

  products: [
    {
      name: "Complete Puja Thali Set",
      slug: "complete-puja-thali-set",
      category: "Puja Essentials",
      description: "A beautifully crafted brass puja thali set containing all essentials for daily worship — thali, diya, agarbatti stand, kumkum container, bell, and kalash. Perfect for home temples and special pujas.",
      shortDescription: "Complete brass puja thali with all worship essentials.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Puja Thali" }],
      saleType: "both",
      rentPrice: 250,
      buyPrice: 1500,
      price: 1500,
      stock: 50,
      isConsumable: false,
      isActive: true,
      featured: true,
    },
    {
      name: "Rudraksha Mala (108 beads)",
      slug: "rudraksha-mala-108",
      category: "Spiritual Items",
      description: "Authentic 5-mukhi Rudraksha mala with 108 beads, sourced from Nepal. Each bead is naturally grown and blessed. Ideal for japa meditation, daily chanting, and spiritual practice.",
      shortDescription: "Authentic 5-mukhi Rudraksha mala for meditation.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Rudraksha Mala" }],
      saleType: "buy",
      buyPrice: 2500,
      price: 2500,
      stock: 30,
      isConsumable: false,
      isActive: true,
      featured: true,
    },
    {
      name: "Ganga Jal (Holy Water) - 500ml",
      slug: "ganga-jal-500ml",
      category: "Sacred Items",
      description: "Pure, unprocessed holy water from the Ganga river in Varanasi. Collected from the ghats during auspicious muhurat. Essential for pujas, havan, and spiritual ceremonies.",
      shortDescription: "Pure holy Ganga water for puja and ceremonies.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Ganga Jal" }],
      saleType: "buy",
      buyPrice: 151,
      price: 151,
      stock: 200,
      isConsumable: true,
      isActive: true,
      featured: true,
    },
    {
      name: "Havan Samagri Kit",
      slug: "havan-samagri-kit",
      category: "Puja Essentials",
      description: "Complete havan samagri kit containing 21 sacred herbs, ghee, camphor, sandalwood powder, and agarbatti. Enough for one complete havan ceremony. All ingredients are natural and sourced from authentic suppliers.",
      shortDescription: "Complete sacred herbs and materials for havan ceremony.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Havan Samagri" }],
      saleType: "buy",
      buyPrice: 800,
      price: 800,
      stock: 100,
      isConsumable: true,
      isActive: true,
      featured: false,
    },
    {
      name: "Brass Diya Set (Pack of 12)",
      slug: "brass-diya-set-12",
      category: "Puja Essentials",
      description: "Handcrafted brass diyas, pack of 12. Perfect for aarti, Dev Deepawali celebrations, and daily puja. Each diya is polished and ready to use with cotton wicks included.",
      shortDescription: "Handcrafted brass diyas for aarti and celebrations.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Brass Diyas" }],
      saleType: "buy",
      buyPrice: 450,
      price: 450,
      stock: 80,
      isConsumable: false,
      isActive: true,
      featured: false,
    },
    {
      name: "Wedding Mandap Decoration Set",
      slug: "wedding-mandap-decoration",
      category: "Wedding Items",
      description: "Complete mandap decoration set including floral hangings, mango leaf torans, kalash set, sacred thread, and decorative items. Available for rent for wedding ceremonies.",
      shortDescription: "Complete mandap decoration for wedding ceremonies.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Mandap Decoration" }],
      saleType: "rent",
      rentPrice: 5000,
      price: 5000,
      stock: 10,
      isConsumable: false,
      isActive: true,
      featured: true,
    },
    {
      name: "Shiva Lingam (Natural Stone)",
      slug: "shiva-lingam-natural",
      category: "Sacred Items",
      description: "Natural Narmada stone Shiva Lingam, hand-polished and consecrated. The unique markings on each lingam are natural and represent the divine union of Shiva and Shakti.",
      shortDescription: "Natural Narmada stone Shiva Lingam, hand-polished.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Shiva Lingam" }],
      saleType: "buy",
      buyPrice: 1100,
      price: 1100,
      stock: 25,
      isConsumable: false,
      isActive: true,
      featured: false,
    },
    {
      name: "Kumkum & Chandan Set",
      slug: "kumkum-chandan-set",
      category: "Puja Essentials",
      description: "Premium quality kumkum (vermillion) and chandan (sandalwood paste) set. Sourced from authentic suppliers. Essential for tilak, puja, and religious ceremonies.",
      shortDescription: "Premium kumkum and chandan for tilak and puja.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Kumkum Chandan" }],
      saleType: "buy",
      buyPrice: 200,
      price: 200,
      stock: 150,
      isConsumable: true,
      isActive: true,
      featured: false,
    },
    {
      name: "Panchamrit Set",
      slug: "panchamrit-set",
      category: "Puja Essentials",
      description: "Ready-to-use Panchamrit set containing milk, curd, honey, ghee, and sugar. Freshly prepared for abhishek ceremonies. Available in packs for individual and group pujas.",
      shortDescription: "Fresh Panchamrit set for abhishek ceremonies.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Panchamrit" }],
      saleType: "buy",
      buyPrice: 350,
      price: 350,
      stock: 100,
      isConsumable: true,
      isActive: true,
      featured: false,
    },
    {
      name: "Havan Kund (Fire Pit)",
      slug: "havan-kund-copper",
      category: "Puja Essentials",
      description: "Traditional copper havan kund (fire pit) for performing havan and yagna ceremonies. Available in various sizes. Comes with a stand and instruction guide.",
      shortDescription: "Traditional copper havan kund for ceremonies.",
      images: [{ url: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana", alt: "Havan Kund" }],
      saleType: "both",
      rentPrice: 500,
      buyPrice: 3500,
      price: 3500,
      stock: 15,
      isConsumable: false,
      isActive: true,
      featured: false,
    },
  ],

  pandits: [
    {
      name: "Pandit Ramesh Shastri",
      slug: "pandit-ramesh-shastri",
      profileImage: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana",
      bio: "Pandit Ramesh Shastri is a renowned Vedic scholar with over 25 years of experience in performing traditional Hindu rituals. Born into a family of priests at Dashashwamedh Ghat, he has deep knowledge of Vedic mantras, astrology, and all major Hindu ceremonies. He specializes in Rudrabhishek, Kaal Sarp Dosh Nivaran, and wedding ceremonies.",
      shortBio: "25+ years experience. Vedic scholar specializing in Rudrabhishek and weddings.",
      experience: 25,
      languages: ["Hindi", "Sanskrit", "English"],
      specializations: ["Rudrabhishek", "Wedding Ceremonies", "Kaal Sarp Dosh", "Graha Shanti"],
      rating: 4.9,
      reviewsCount: 156,
      price: 5100,
      priceNote: "Starting price. Varies by ceremony type.",
      availability: "available",
      isActive: true,
      featured: true,
    },
    {
      name: "Pandit Suresh Tiwari",
      slug: "pandit-suresh-tiwari",
      profileImage: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana",
      bio: "Pandit Suresh Tiwari comes from a lineage of respected Kashi pandits. With 18 years of experience, he is well-versed in Satyanarayan Katha, Griha Pravesh, and Mundan ceremonies. Known for his patient explanations of each ritual's significance to families.",
      shortBio: "18 years experience. Expert in Satyanarayan Katha and family ceremonies.",
      experience: 18,
      languages: ["Hindi", "Sanskrit", "Bhojpuri"],
      specializations: ["Satyanarayan Katha", "Griha Pravesh", "Mundan", "Naming Ceremony"],
      rating: 4.7,
      reviewsCount: 98,
      price: 3500,
      priceNote: "Starting price for basic ceremonies.",
      availability: "available",
      isActive: true,
      featured: true,
    },
    {
      name: "Acharya Vishwanath Dubey",
      slug: "acharya-vishwanath-dubey",
      profileImage: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana",
      bio: "Acharya Vishwanath Dubey is a revered Vedic astrologer and ritual expert with 30+ years of experience. He holds a Shastri degree from Sampurnanand Sanskrit University, Varanasi. Specializes in complex pujas like Kaal Sarp Dosh Nivaran, Pitru Dosh puja, and Nav Graha Shanti.",
      shortBio: "30+ years. Vedic astrologer and expert in complex dosham pujas.",
      experience: 30,
      languages: ["Hindi", "Sanskrit", "English", "Gujarati"],
      specializations: ["Kaal Sarp Dosh", "Pitru Dosh", "Nav Graha Shanti", "Vastu Shanti", "Astrology Consultation"],
      rating: 4.8,
      reviewsCount: 203,
      price: 7500,
      priceNote: "Consultation fee included.",
      availability: "available",
      isActive: true,
      featured: true,
    },
    {
      name: "Pandit Govind Mishra",
      slug: "pandit-govind-mishra",
      profileImage: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana",
      bio: "Pandit Govind Mishra specializes in wedding ceremonies and engagement rituals. With 15 years of experience, he has conducted over 500 weddings in Varanasi. Known for making ceremonies joyful while maintaining Vedic authenticity.",
      shortBio: "15 years, 500+ weddings. Specialist in marriage ceremonies.",
      experience: 15,
      languages: ["Hindi", "Sanskrit", "English"],
      specializations: ["Wedding Ceremonies", "Engagement", "Haldi Ceremony", "Tilak Ceremony"],
      rating: 4.6,
      reviewsCount: 134,
      price: 5100,
      priceNote: "Wedding package. Other ceremonies priced differently.",
      availability: "available",
      isActive: true,
      featured: false,
    },
    {
      name: "Pandit Anand Sharma",
      slug: "pandit-anand-sharma",
      profileImage: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana",
      bio: "Pandit Anand Sharma is a young and energetic priest known for conducting pujas at various ghats of Varanasi. With 10 years of experience, he brings a modern approach while respecting ancient traditions. Expert in Ganga Aarti, boat pujas, and Mahamrityunjay Jaap.",
      shortBio: "10 years experience. Modern approach with ancient wisdom.",
      experience: 10,
      languages: ["Hindi", "Sanskrit", "English", "Bengali"],
      specializations: ["Ganga Aarti", "Boat Puja", "Mahamrityunjay Jaap", "Sunderkand Path"],
      rating: 4.5,
      reviewsCount: 76,
      price: 2500,
      priceNote: "Affordable packages for students and young families.",
      availability: "available",
      isActive: true,
      featured: false,
    },
    {
      name: "Pandit Kamlesh Pathak",
      slug: "pandit-kamlesh-pathak",
      profileImage: "https://placehold.co/800x600/FFFEFB/E8820F?text=Kashi+Vandana",
      bio: "Pandit Kamlesh Pathak is an authority on Pitru ceremonies and shraddha rituals. With 20 years of experience serving families at Manikarnika and Harishchandra Ghats, he handles all last rites and post-death ceremonies with utmost sensitivity and proper Vedic procedures.",
      shortBio: "20 years experience in Pitru ceremonies and last rites.",
      experience: 20,
      languages: ["Hindi", "Sanskrit"],
      specializations: ["Last Rites", "Shraddha", "Pind Daan", "Pitru Tarpan", "Asthi Visarjan"],
      rating: 4.8,
      reviewsCount: 89,
      price: 5100,
      priceNote: "Ceremony specific pricing.",
      availability: "available",
      isActive: true,
      featured: false,
    },
  ],

  reviews: [
    {
      entityType: "pandit",
      customerName: "Rajesh Kumar",
      rating: 5,
      review: "Pandit Ramesh Shastri ji performed Rudrabhishek for our family. The experience was truly divine. He explained every mantra and ritual patiently. Highly recommended!",
      isApproved: true,
    },
    {
      entityType: "pandit",
      customerName: "Priya Verma",
      rating: 5,
      review: "We had our engagement ceremony conducted by Pandit Suresh Tiwari ji. Everything was perfectly arranged and the ceremony was beautiful. Thank you!",
      isApproved: true,
    },
    {
      entityType: "pandit",
      customerName: "Amit Gupta",
      rating: 4,
      review: "Acharya Vishwanath ji did Kaal Sarp Dosh puja for us. Very knowledgeable and thorough. The puja took about 5 hours but every ritual was done properly.",
      isApproved: true,
    },
    {
      entityType: "ghat",
      customerName: "Sneha Patel",
      rating: 5,
      review: "The Ganga Aarti at Dashashwamedh Ghat was a life-changing experience. Vhavah Vandana arranged everything perfectly — best seats, explanation of rituals, and prasad. Must visit!",
      isApproved: true,
    },
    {
      entityType: "ghat",
      customerName: "Vikram Singh",
      rating: 4,
      review: "Beautiful morning puja at Assi Ghat. The atmosphere was serene and spiritual. The pandit was very knowledgeable. Only wish there was better parking nearby.",
      isApproved: true,
    },
  ],
};

// POST /api/seed — Seed the database (dev only)
export async function POST(request) {
  try {
    // Only allow in development
    if (process.env.NODE_ENV === "production") {
      return NextResponse.json(
        { success: false, error: "Seeding not allowed in production" },
        { status: 403 }
      );
    }

    await connectDB();

    // Clear existing data
    await Promise.all([
      Ghat.deleteMany({}),
      Service.deleteMany({}),
      Product.deleteMany({}),
      Pandit.deleteMany({}),
      Review.deleteMany({}),
    ]);

    // Seed data
    const [ghats, services, products, pandits] = await Promise.all([
      Ghat.insertMany(SEED_DATA.ghats),
      Service.insertMany(SEED_DATA.services),
      Product.insertMany(SEED_DATA.products),
      Pandit.insertMany(SEED_DATA.pandits),
    ]);

    // Seed reviews with entity references
    const reviewsToInsert = SEED_DATA.reviews.map((review, index) => {
      if (review.entityType === "pandit") {
        return { ...review, entityId: pandits[index % pandits.length]._id };
      } else {
        return { ...review, entityId: ghats[index % ghats.length]._id };
      }
    });
    const reviews = await Review.insertMany(reviewsToInsert);

    return NextResponse.json({
      success: true,
      message: "Database seeded successfully",
      counts: {
        ghats: ghats.length,
        services: services.length,
        products: products.length,
        pandits: pandits.length,
        reviews: reviews.length,
      },
    });
  } catch (error) {
    console.error("POST /api/seed error:", error);
    return NextResponse.json(
      { success: false, error: "Seeding failed: " + error.message },
      { status: 500 }
    );
  }
}
